{
 "title": "k6 Prometheus",
 "description": "Visualize k6 OSS results stored in Prometheus",
 "tags": [
  "prometheus",
  "k6"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Prometheus DS", "query": "prometheus" },
   { "name": "testid", "label": "Test ID", "query": { "query": "label_values(testid)" } },
   { "name": "quantile_stat", "label": "Trend Metrics Query", "query": { "query": "metrics(k6_http_req_duration_)" } },
   { "name": "adhoc_filter", "label": "AdhocFilter" }
  ]
 },
 "panels": [
  { "title": "Performance Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Performance Overview",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "avg(k6_vus{testid=~\"$testid\"})",
     "legendFormat": "vus"
    },
    {
     "expr": "avg(k6_http_req_duration_$quantile_stat{testid=~\"$testid\"})",
     "legendFormat": "http_req_duration_$quantile_stat"
    },
    {
     "expr": "sum(irate(k6_http_reqs_total{testid=~\"$testid\"}[$__rate_interval]))",
     "legendFormat": "http_req_s"
    },
    {
     "expr": "sum(irate(k6_http_reqs_total{testid=~\"$testid\", expected_response=\"false\"}[$__rate_interval]))",
     "legendFormat": "http_req_s_errors"
    }
   ]
  },
  {
   "title": "HTTP requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(k6_http_reqs_total{testid=~\"$testid\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP request failures",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(k6_http_reqs_total{testid=~\"$testid\", expected_response=\"false\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Peak RPS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(irate(k6_http_reqs_total{testid=~\"$testid\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Request Duration",
   "type": "stat",
   "description": "Select a different Stat to change the query",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(k6_http_req_duration_$quantile_stat{testid=~\"$testid\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transfer Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(irate(k6_data_sent_total{testid=~\"$testid\"}[$__rate_interval]))",
     "legendFormat": "data_sent"
    },
    {
     "expr": "avg(irate(k6_data_received_total{testid=~\"$testid\"}[$__rate_interval]))",
     "legendFormat": "data_received"
    }
   ]
  },
  {
   "title": "Iterations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(k6_iteration_duration_$quantile_stat{testid=~\"$testid\"})",
     "legendFormat": "iteration_duration_$quantile_stat"
    },
    {
     "expr": "avg(k6_dropped_iterations_total{testid=~\"$testid\"})",
     "legendFormat": "dropped_iterations"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Response Times",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(k6_http_req_duration_p90{testid=~\"$testid\"})",
     "legendFormat": "90%"
    },
    {
     "expr": "avg(k6_http_req_duration_p95{testid=~\"$testid\"})",
     "legendFormat": "95%"
    }
   ]
  },
  {
   "title": "Slow 90.0th Percentile",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (method, url) (k6_http_req_duration_p90)",
     "legendFormat": "{{method}} {{url}}"
    },
    { "expr": "0.3", "legendFormat": "limit" }
   ]
  },
  {
   "title": "Slow 95.0th Percentile",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (method, url) (k6_http_req_duration_p95{testid=~\"$testid\"})",
     "legendFormat": "{{method}} {{url}}"
    },
    { "expr": "0.6", "legendFormat": "limit" }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Success/Failed Requests",
   "type": "piechart",
   "description": "Request distribution by success and failure",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(k6_http_reqs_total{testid=~\"$testid\", expected_response=\"false\"}) by (job) / sum(k6_http_reqs_total{testid=~\"$testid\"}) by (job) * 100",
     "legendFormat": "Failed Requests"
    },
    {
     "expr": "sum(k6_http_reqs_total{testid=~\"$testid\", expected_response=\"true\"}) by (job) / sum(k6_http_reqs_total{testid=~\"$testid\"}) by (job) * 100",
     "legendFormat": "Successful Requests"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "table",
   "description": "Errors seen, grouped by url, method and status code",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "sum without(expected_response, proto) (k6_http_reqs_total{testid=~\"$testid\", expected_response=\"false\"})",
     "legendFormat": "min"
    }
   ]
  },
  {
   "title": "Request Failure Rate",
   "type": "table",
   "description": "Rate of failed requests by url and method ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "sum(rate(k6_http_reqs_total{expected_response=\"false\"}[$__rate_interval])) by(name, method) / on (name, method) (sum(rate(k6_http_reqs_total{}[$__rate_interval])) by (name, method) > 0) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Spike",
   "type": "timeseries",
   "description": "Request error spikes by url and method",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(k6_http_reqs_total{expected_response=\"false\"}[$__rate_interval])) by(name, method) / on (name, method) sum(rate(k6_http_reqs_total{}[$__rate_interval])) by (name, method) * 100",
     "legendFormat": "{{method}} - {{name}}"
    },
    { "expr": "1.0", "legendFormat": "limit" }
   ]
  },
  {
   "title": "HTTP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP Latency Timings",
     "type": "timeseries",
     "description": "Select a different Stat to change the query\n\n<a href=\"https://k6.io/docs/using-k6/metrics/reference/#http\" target=\"_blank\">HTTP-specific built-in metrics</a>",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(k6_http_req_blocked_$quantile_stat{testid=~\"$testid\"})",
       "legendFormat": "http_req_blocked_$quantile_stat"
      },
      {
       "expr": "avg(k6_http_req_tls_handshaking_$quantile_stat{testid=~\"$testid\"})",
       "legendFormat": "http_req_tls_handshaking_$quantile_stat"
      },
      {
       "expr": "avg(k6_http_req_sending_$quantile_stat{testid=~\"$testid\"})",
       "legendFormat": "http_req_sending_$quantile_stat"
      },
      {
       "expr": "avg(k6_http_req_waiting_$quantile_stat{testid=~\"$testid\"})",
       "legendFormat": "http_req_waiting_$quantile_stat"
      },
      {
       "expr": "avg(k6_http_req_receiving_$quantile_stat{testid=~\"$testid\"})",
       "legendFormat": "http_req_receiving_$quantile_stat"
      },
      {
       "expr": "avg(k6_http_req_duration_$quantile_stat{testid=~\"$testid\"})",
       "legendFormat": "http_req_duration_$quantile_stat"
      }
     ]
    },
    {
     "title": "HTTP Latency Stats",
     "type": "timeseries",
     "description": "Select a different Stat to change the query",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(k6_http_req_duration_$quantile_stat{testid=~\"$testid\"})",
       "legendFormat": "http_req_duration_$quantile_stat"
      },
      {
       "expr": "avg(k6_http_req_duration_$quantile_stat{testid=~\"$testid\", expected_response=\"true\"})",
       "legendFormat": "success_http_req_duration_$quantile_stat"
      },
      {
       "expr": "avg(k6_http_req_duration_$quantile_stat{testid=~\"$testid\", expected_response=\"false\"})",
       "legendFormat": "errors_http_req_duration_$quantile_stat"
      }
     ]
    },
    {
     "title": "HTTP Request Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(irate(k6_http_reqs_total{testid=~\"$testid\"}[$__rate_interval]))",
       "legendFormat": "http_req_s"
      },
      {
       "expr": "sum(irate(k6_http_reqs_total{testid=~\"$testid\", expected_response=\"false\"}[$__rate_interval]))",
       "legendFormat": "http_req_s_errors"
      },
      {
       "expr": "sum(irate(k6_http_reqs_total{testid=~\"$testid\", expected_response=\"true\"}[$__rate_interval]))",
       "legendFormat": "http_req_s_success"
      }
     ]
    },
    {
     "title": "Requests by URL",
     "type": "table",
     "description": "min/max/p95/p99 depends on the available Quantile Stats",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 71 },
     "targets": [
      {
       "expr": "avg by(name, method, status) (k6_http_req_duration_min{testid=~\"$testid\"})",
       "legendFormat": "min"
      },
      {
       "expr": "avg by(name, method, status) (k6_http_req_duration_max{testid=~\"$testid\"})",
       "legendFormat": "max"
      },
      {
       "expr": "avg by(name, method, status) (k6_http_req_duration_p95{testid=~\"$testid\"})",
       "legendFormat": "p95"
      },
      {
       "expr": "avg by(name, method, status) (k6_http_req_duration_p99{testid=~\"$testid\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Checks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 },
   "collapsed": true,
   "panels": [
    {
     "title": "Checks list",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 739 },
     "targets": [
      {
       "expr": "round(k6_checks_rate{testid=~\"$testid\"}, 0.1)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Checks Success Rate (aggregate individual checks)",
     "type": "timeseries",
     "description": "Filter by check name to query a particular check",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 739 },
     "fieldConfig": { "defaults": { "unit": "%" } },
     "targets": [
      {
       "expr": "avg(round(k6_checks_rate{testid=~\"$testid\"}, 0.1)*100)",
       "legendFormat": "k6_checks_rate"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 747 },
     "options": {
      "content": "### Visualize other k6 results  \n\nAt the top of the dashboard, click `Add` and select `Visualization` from the dropdown menu. Choose the visualization type and input the PromQL queries for the `k6_` metric(s).\n\nAlternatively, click on the `Explore` icon on the menu bar and input the queries for the `k6_` metric(s). From `Explore`, you can add new Panels to this dashboard. \n\nNote that all <a href=\"https://k6.io/docs/using-k6/metrics/\" target=\"_blank\">k6 metrics</a> are prefixed with the `k6_` namespace when sent to Prometheus."
     }
    }
   ]
  }
 ]
}